language: python
install:
  - pip install codecov coveralls tox
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
script:
  - tox -- --cov --cov-report=
after_success:
  - coveralls
  - codecov
env:
  - TOXENV=py27-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
